services:
  nginx:
    image: nginx:latest
    container_name: my_nginx_container
    ports:
      - "80:80"
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./generate_certificates.sh:/etc/nginx/generate_certificates.sh 
    command: /bin/bash -c "/etc/nginx/generate_certificates.sh && nginx -g 'daemon off;'"
    network_mode: "host"
    
  db:
    image: mysql:latest
    container_name: my_mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "@ztegc4df9f4e"
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - ../Database/SQLQuery_1.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    command: --init-file=/docker-entrypoint-initdb.d/init.sql
    network_mode: "host"

volumes:
  mysql_data:
