services:
  db:
    build:
      context: ../
      dockerfile: ./docker/dockerfile/mysql.dockerfile
    container_name: my_mysql_container
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      my_network:
        ipv4_address: 172.21.0.3

  be:
    build:
      context: ../
      dockerfile: ./docker/dockerfile/be.dockerfile
    container_name: my_be_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      my_network:
        ipv4_address: 172.21.0.4

  nginx:
    build:
      context: ./
      dockerfile: ./dockerfile/nginx.dockerfile
    container_name: my_nginx_container
    ports:
      - "80:80"
      - "8433:8433"
    depends_on:
      - be
      - certbot-init
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
      - /tmp/certbot:/tmp/certbot
    networks:
      my_network:
        ipv4_address: 172.21.0.2

  certbot:
    build:
      context: ../
      dockerfile: ./docker/dockerfile/certbot.dockerfile
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  certbot-init:
    build:
      context: ../
      dockerfile: ./docker/dockerfile/certbot.dockerfile
    container_name: certbot_init
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
      - /tmp/certbot:/tmp/certbot
    command: >
      sh -c "certbot certonly --webroot -w /data/letsencrypt  -d seller-technology.langbach.io.vn  --email bachlang364@gmail.com --agree-tos  --force-renewal --non-interactive  && touch /tmp/certbot/done"
    networks:
      my_network:
        ipv4_address: 172.21.0.5

volumes:
  mysql_data:
  certs:
  certs-data:


networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
