services:
  nginx:
    build:
      context: ./
      dockerfile: ./dockerfile/nginx.dockerfile
    container_name: my_nginx_container
    ports:
      - "8000:8000"
      - "8443:8443"
    networks:
      - my_network

  db:
    build:
      context: ../
      dockerfile: ./docker/dockerfile/mysql.dockerfile
    container_name: my_mysql_container
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  be:
    build:
      context: ../
      dockerfile: ./docker/dockerfile/be.dockerfile
    container_name: my_be_container
    ports:
      - "8080:8080"
      - "5050:5050"
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
